### ISSUE TITLE
deligating constructor

### ISSUE THREAD

**Issue by wigiglenekit** [RaphielSh/MultiDimOperations#1]
Поменяй конструктор копий на deligating constructor
https://www.geeksforgeeks.org/constructor-delegation-c/

**Comment by RaphielSh** [comment]
не совсем понимаю как это будет работать. Это похоже на вызов функции c_vector().

**Comment by RaphielSh** [comment]
Если это конструктор копирования, то передаваться должен объект, а в твоем примере передается вектор

**Comment by RaphielSh** [comment]
тогда почему вектор передается в виде c_vector(vector)

**Comment by RaphielSh** [comment]
или это перегрузка оператора скобок?

**Comment by RaphielSh** [comment]
Это я понял. Просто в issue было изначально сказано о конструкторе копирования
